# Generated by Django 4.0.4 on 2022-04-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='descount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='descount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='state',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='state',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='historicalproductimage',
            name='state',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='state',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='State'),
        ),
    ]
