# Generated by Django 4.0.4 on 2022-04-15 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_historicalproduct_descount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproductimage',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='images_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images_product',
        ),
        migrations.AddField(
            model_name='historicalproductimage',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_product', to='products.product'),
        ),
    ]
