# Generated by Django 4.0.4 on 2022-04-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_image_historicalproductimage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='historicalproductimage',
            name='image_upload',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Product Image Upload'),
        ),
        migrations.AddField(
            model_name='historicalproductimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Product Image URL'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Product Image Upload'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Product Image URL'),
        ),
    ]
