# Generated by Django 4.0.4 on 2022-04-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_historicalproduct_descount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='descount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Discount Rate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Discount Rate'),
        ),
    ]
