# Generated by Django 4.0.4 on 2022-04-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_historicalproduct_descount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproductimage',
            name='image_upload',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_upload',
        ),
    ]
