# Generated by Django 4.0.4 on 2022-04-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='profiles.role'),
        ),
    ]
