# Generated by Django 4.0.4 on 2022-04-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.role', verbose_name='Role'),
        ),
    ]
